### ISSUE TITLE
Improve migration script

### ISSUE THREAD

**Issue by rymurr** [sundeck-io/OpsCenter#101]
Currently `internal.migrate_if_necessary` only works for additions to the base tables. eg if Snowflake adds fields to the `query_history` table. We have to make it more flexible to be able to support:
* removing of columns from base tables
* additions of columns by us (eg #88 ) 

This is especially tricky right now as we use `*` in projections in a number of places, therefore making the ordinal and total number of columns in these tables important. Before this issue is worked on we therefore need to close #100

Once that is done we should be able to update the migration scripts to simply add columns w/o regard to order and be able to easily remove columns if required. We should also be able ot add columns of our own (eg #88 or #86)

**Comment by jinfengni** [comment]
From @rymurr :

Test cases:
- snowflake adds a column (no sundeck update)
- snowflake removes a column (no sundeck update)
- we change our ddl and update the app by adding a column
- we change our ddl and updat the app by removing a column

**Comment by jinfengni** [comment]
Migrate:
view : `INTERNAL_REPORTING.QUERY_HISTORY_COMPLETE_AND_DAILY`, 
table: `INTERNAL_REPORTING_MV.QUERY_HISTORY_COMPLETE_AND_DAILY` or `INTERNAL_REPORTING_MV.QUERY_HISTORY_COMPLETE_AND_DAILY_INCOMPLETE`. 

With the pr of #101, we removed * in the projections, and used explicitly column list in the view DDL.

- Case 1:  snowflake adds a column (no sundeck update)
    If we do not explicitly add the new column in the column list in the view DDL,  nothing is required to be changed.  The view and table remains in sync. 

- Case 2: snowflake adds a column. sundeck adds the new column of query_history into the view DDL. 
   The migrate script should detect the table and view is not in sync mode.  The migrate script will add the new column to the table.

- Case 3: snowflake removes a column (no sundeck update)
   The removal of a column in query_history will breaks the view DDL.  If Sundeck does not update the view DDL and re-deploy, the App will break.

- Case 4:   snowflake removes a column. sundeck removes the column from view DDL
   The migrate script should detect the table and view is not in sync mode. The migrate script will drop the column from the table. 

- Case 5:  Sundeck change our ddl and update the app by adding a column
    The migrate script should detect the table and view is not in sync mode. The migrate script will add the new column to the table. 

- Case 6: Sundeck change our ddl and update the app by removing a column
     The migrate script should detect the table and view is not in sync mode. The migrate script will drop the column from the table.
