### ISSUE TITLE
After API integration permission view switches to home page

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#122]
https://github.com/sundeck-io/OpsCenter/assets/104043363/9e80f546-2e1a-41c0-93aa-73a3ac79fb00

**Comment by anshuldata** [comment]
This is streamlit behavior so we can't really fix page redirection. Enhanced message to include that "user should revisit page to complete next step". Added this message with PR https://github.com/sundeck-io/OpsCenter/pull/127
