### ISSUE TITLE
Create fine grained cost control artifacts in bootstrap

### ISSUE THREAD

**Issue by rymurr** [sundeck-io/OpsCenter#125]
This moves the table/udf/proc definitions from the sundeck predefined flow to opscenter.

- [x] boolean flag (defautls to on) to generate consumption data
- [x] probe task turned on if len(probes) >= 0 or bool above is true
- [x] UDF to send consumption to Sundeck for consumption limit hook
- [x] stored proc to generate consumption data and sedn to udf
- [x]  add stored proc to probe task and if statement o skip if bool is off
- [x] circumvent the query history table function limit of 10k rows per call
- [x] revert https://github.com/sundeck-io/OpsCenter/pull/199 to re-enable after predefined probes & labels are released

**Comment by joshelser** [comment]
I spent a part of day testing this and everything looks good to me. I'll resolve this issue when it gets released.
