### ISSUE TITLE
Create a report based on the fine graned access control tables

### ISSUE THREAD

**Issue by rymurr** [sundeck-io/OpsCenter#126]
This should show
1. credits used today for users and roles
2. historical usage
3. description of what is being sent to sundeck and how often
4. have an option to turn off sending to sundeck

**Comment by joshelser** [comment]
Double-checking: we decided to put this on the back-burner for now as we believe it is largely duplicated by the existing query activity report?

**Comment by rymurr** [comment]
yes, ive dropped it in priority in the milestone accordingly
