### ISSUE TITLE
Loaded cost sometimes < unloaded cost in view warehouse_hourly_utilization

### ISSUE THREAD

**Issue by robertmaybin** [sundeck-io/OpsCenter#136]
Seen on my account WUAXXXXX, when running the following query:
```sql
select * from 
opscenter.reporting.warehouse_hourly_utilization
where 
warehouse_id = 23
order by period desc
limit 100
;
```

The following results are returned:
<img width="647" alt="image" src="https://github.com/sundeck-io/OpsCenter/assets/22859626/e6706245-ca44-489e-acab-071cdf922c32">

In the case of the first row in the results, loaded cost is much less than unloaded cost (the other rows seem right-side-up).

**Comment by jacques-n** [comment]
My guess is this has to do with time differences between when warehouse sessions and query history are analyzed (they are two independent tasks). So if query history generates unloaded cost but warehouse sessions are older, we'll not see loaded cost. If the numbers are correct/become correct when we're not on the bubble condition (e.g. today), then this is probably the case.

**Comment by rymurr** [comment]
I've been monitoring over the past few days and this indeed only occurs in today's data and is corrected when the maintenance task next runs.
