### ISSUE TITLE
Utilization metric in warehouse_*_utilization should be a number

### ISSUE THREAD

**Issue by robertmaybin** [sundeck-io/OpsCenter#137]
Am seeing NULL as utilization values in warehouse_daily_utilization and warehouse_hourly_utilization views.  Expectation is that utilization should always be a number between 0 and 1. 

This seems to happen when cost values are very small (i.e. on the order of 10^-9 or less); possible a simple coalesce to 0 will solve.

**Comment by rymurr** [comment]
@robertmaybin we are explicitly saying if cost is 0 then the utlilization should be NULL. See: https://github.com/sundeck-io/OpsCenter/blob/main/bootstrap/020_warehouse_utilzation.sql#L33

The intention here (I believe) is to differentiate between low utilization and no usage. LMK if that makes sense, if so I will close this.

**Comment by rymurr** [comment]
ping @robertmaybin
