### ISSUE TITLE
Possible wrong direction on condition in QUERY_HISTORY_COMPLETE_AND_DAILY

### ISSUE THREAD

**Issue by rymurr** [sundeck-io/OpsCenter#143]
line 10 has `IFF(index = PEROID_PLUS...` it is possible that this condition has been reveresed and is causing dups in #31

**Comment by jacques-n** [comment]
It seems like this would likely be a problem in the warehouse version of this query as well (since the two are basically copies)

**Comment by jacques-n** [comment]
Let's make sure that this change does not force rewrite of all data.
