### ISSUE TITLE
Create library of Cypress commands for accessing Snowflake database

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#165]
In many UI tests we would love to have ability to validate if some action took effect and it's not really possible without checking database. For example, see issue #161 , after setting check boxes to ON, I would like to know the state of the task (enabled/disabled)

Cypress supports ability to connect to a database and runqueries inside Cypress test, see [here](https://www.browserstack.com/guide/cypress-database-testing#:~:text=Yes.,using%20the%20Cypress%20test%20runner.)****

Cypress support custom commands as well, see [here](https://docs.cypress.io/api/cypress-api/custom-commands)

And lastly, @doronrosenberg , has prototyped connecting to snowflake with node.js driver already, we should revive it and take advantage of it.

**Comment by susannahmarcus** [comment]
Should we make an e2e testing specific db (created at time of tests)? 
>  This would yield the most consistent results, but would not mirror the env users see as closely as it wouldn't have the pre-baked labels. That said, with the issues we've hit already when testing streamlit, it might be a good idea to start with testing specific and get that stable first... 🤔

**Comment by rymurr** [comment]
Each PR is run against its own db already. Is that what you are asking?

**Comment by susannahmarcus** [comment]
not exactly. I'm wondering if we should have the e2e tests on its own db or not. So we don't have the other tests labels and stuff that pops up from them being connected to the same db. And or should we just use the same db but drop everything (pre-canned labels/probes included) so it's like new when the tests run.

**Comment by susannahmarcus** [comment]
failed a few times so needing to look into it a bit more: 

1. https://github.com/sundeck-io/OpsCenter/actions/runs/6411715062/job/17407878340
2. https://github.com/sundeck-io/OpsCenter/actions/runs/6411667710/job/17407570477
