### ISSUE TITLE
https://docs.sundeck.io/opscenter/quickstart/complete-setup/ page has incorrect information

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#166]
Setup has changed.

**Comment by rymurr** [comment]
any more detail on this? What specifically is the issue?

**Comment by rymurr** [comment]
ping @vqmarkman

**Comment by vqmarkman** [comment]
Documentation:

<img width="826" alt="Screenshot 2023-08-28 at 8 20 15 AM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/ef68cbfc-65d2-4130-b203-565cbe8e0a95">

Reality:

<img width="1595" alt="Screenshot 2023-08-28 at 8 22 28 AM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/a0137e29-0d65-4bca-9d6d-26a31de6d495">

**Comment by vqmarkman** [comment]
In review in @robertmaybin queue.
