### ISSUE TITLE
Cypress test failed twice on Probes test

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#174]
https://github.com/sundeck-io/OpsCenter/actions/runs/5903962527/job/16015013254

@vqmarkman do you have any ideas? I haven't been watching these closely enough to know what has changed. Has the "connect to sundeck" expander window always been there in cypress tests?

My only guess is that the expander window is blocking the probe from showing up? I feel like if it was a set up problem, we would have known long ago.

**Comment by joshelser** [comment]
I saw this fail twice after merging https://github.com/sundeck-io/OpsCenter/commit/eee8e067ed6b081c21c88173212268d271d914f9 but am very skeptical that this commit could have actually broken this cypress test.

**Comment by vqmarkman** [comment]
The problem that I see in the Cypress video is that test can't find probe in the DOM object when it tries to delete it.

Got the latest code and:
* Ran probes test at least 10 times locally - works every single time
* Made sure that probe from the test was actually created in Snowflake (it was):

<img width="1619" alt="successfully_created_probe" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/2cf8d32c-e5bb-4fc9-a3f6-a3313e03f8bb">

* Test does not fail for me when I run it as part of the list of tests locally this way: `yarn cypress run`

Next step: consult with experts @doronrosenberg  and @susannahmarcus

**Comment by vqmarkman** [comment]
@jinfengni ran into the same problem as well in his PR [here](https://github.com/sundeck-io/OpsCenter/actions/runs/5898375750/job/15999335154?pr=172)
