### ISSUE TITLE
Warehouse Activity reports shows costs 100x over Query Activity report on one day

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#177]
In one of our internal accounts, I see that the reported cost on a given day (Aug 10th) by warehouse is ~100x over the equivalent days' cost on the query activity report.

I think @rymurr might have been doing some work on snowpark that day, as the majority of the cost is associated with a similarly named warehouse.

I'm guessing it's accurate that there were no "traditional" queries being run at the same time, however, it's a little scary that I can't find an association of where this cost is coming from through opscenter. Maybe we could make a report which can describe snowpark usage?

**Comment by rymurr** [comment]
This appears to be some missing data in the account in question, starting on Aug 8 the data volume in enriched query history doesn't match up with account usage. Still investigating why.
