### ISSUE TITLE
tool tips for Wrehouse Heatmap appear wrong

### ISSUE THREAD

**Issue by ron-sundeck** [sundeck-io/OpsCenter#184]
In screen shots below, week numbers increase from top to bottom. dates increase from bottom to top. One of the two is wrong.

<img width="988" alt="Screen Shot 2023-08-23 at 10 35 44 AM" src="https://github.com/sundeck-io/OpsCenter/assets/114949426/6be1d1d7-6662-462c-a331-c8e68abb0954">
<img width="1031" alt="Screen Shot 2023-08-23 at 10 35 36 AM" src="https://github.com/sundeck-io/OpsCenter/assets/114949426/8b44b8da-3452-40aa-a004-a0d99eaaf202">

**Comment by rymurr** [comment]
The method we used to do heatmaps was deprecated and had all kinds of funny edge cases. Using the newer way of doing heatmaps in plotly fixes this.
