### ISSUE TITLE
Heatmap missing tiles

### ISSUE THREAD

**Issue by ron-sundeck** [sundeck-io/OpsCenter#185]
A heat map of 7/1/23 - 8/1/23 is missing tiles

The rows with incomplete weeks (top most and bottom most) have tool tips of "null."
Week 30 covers 7/3-7/9 (where 7/9 is at left most) and then 7/3 is on its immediate right.
Week 27 covers 7/24 - 7/30 (where 7/30 is left most)
Weird

<img width="1187" alt="Screen Shot 2023-08-23 at 10 40 21 AM" src="https://github.com/sundeck-io/OpsCenter/assets/114949426/e0431636-c302-4330-b9ba-d46e56ae0064">

**Comment by rymurr** [comment]
So this is pretty weird. We only take the past 30 days which means we don't have complete weeks. Hence hte empty values in the top and bottom rows.
The reason they are weirdly ordered is the sunday of week 1 was being put in cell 0,0. Basically there is a difference between how the weeks are calculated (using Mon - Sun) and how the cells are labelled (Sun - Sat).
