### ISSUE TITLE
"Long queries" probe is going to kill streamlit after 10 minutes if turned on without modifications 

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#201]
Probe definition:

<img width="1468" alt="Screenshot 2023-08-28 at 12 26 22 PM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/10a9af06-8182-45f4-9460-1eb48ff38d8b">

If user decides to click the check box "Cancel the query", streamlit is going to die after 10 minutes.

Our documentation examples have this check:

<img width="756" alt="Screenshot 2023-08-28 at 11 35 24 AM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/240b9db8-8584-486f-ad6f-73a9c2a09c47">

I think it will be very bad first user experience if we don't add filtering streamlit out.

**Comment by jinfengni** [comment]
I'm going to add `NOT (query_text ilike \'execute streamlit%\')` to the probe conditions in all our predefined probes ('Long Queries' and 'Big Readers').

**Comment by rymurr** [comment]
closed by #202
