### ISSUE TITLE
Heatmap should be on front page of OpsCenter

### ISSUE THREAD

**Issue by ron-sundeck** [sundeck-io/OpsCenter#215]
let's add the report visualization to the front, after welcome blurb.

**Comment by joshelser** [comment]
I will add a header to the report that says warehouse heatmap

**Comment by rymurr** [comment]
Why do we want this @ron-sundeck ? Doesn't seem like the most useful/actionable report to put in the front page and we have a ticket open in this sprint (#89) to have a more coherent design for the front page.
