### ISSUE TITLE
group name could conflict with column from query_history

### ISSUE THREAD

**Issue by jinfengni** [sundeck-io/OpsCenter#223]
When create a label, we only verified that label name does not conflict with column in `query_history` view.  However, for grouped labels,  the group name is added as a new column in `labeled_query_history` view, in stead of label name.  

For instance, tried to create a grouped label, with group_name = `QUERY_TEXT`.  Hit the following error:

`SnowparkSQLException: (1304): 01aeaeff-0503-8271-0062-500303760c8e: 002025 (42S21): 01aeaeff-0503-8271-0062-500303760c8e: Uncaught exception of type 'STATEMENT_ERROR' on line 33 at position 4 : Uncaught exception of type 'STATEMENT_ERROR' on line 35 at position 4 : SQL compilation error: duplicate column name 'QUERY_TEXT'`

![Screen Shot 2023-08-31 at 2 19 44 PM](https://github.com/sundeck-io/OpsCenter/assets/5742011/3b0156df-8cbb-4d6a-b6d2-0481d26952ae)

**Comment by jinfengni** [comment]
Also, looking at the code, I think the current code does not verify the uniqueness of group name for grouped labels.  This will hit similar error if user creates two groups with same names.

**Comment by rymurr** [comment]
closed in #227
