### ISSUE TITLE
LABELED_QUERY_HISTORY loses grant after label modification

### ISSUE THREAD

**Issue by jacques-n** [sundeck-io/OpsCenter#23]
The final perms bootstrap setup script ensures all `REPORTING` views are visible publicly on install. However, label modification will do replace the `LABELED_QUERY_HISTORY` view each time label definitions are changed. Since future grants are not possible on application schemas (afaict), we need to ensure that the `CREATE OR REPLACE` includes the `COPY GRANTS` operation. Otherwise, the view disappears after setup when a user makes a modification.

A workaround until we get a fix is users can run this query:
```
call admin.run_as_app($$
begin
    grant select on view REPORTING.LABELED_QUERY_HISTORY to application role public_;
    grant select on view REPORTING.LABELED_QUERY_HISTORY to application role read_only;
    grant select on view REPORTING.LABELED_QUERY_HISTORY to application role admin;
end;
$$);
```

**Comment by jinfengni** [comment]
I could reproduce the issue with App installed through Marketplace, but could not reproduce it using local streamlit App through `deploy/devdeploy.py`.

**Comment by jinfengni** [comment]
With Versioned App development local deployment, I could reproduce the issue.
