### ISSUE TITLE
Try out st.experimental_connection for local streamlit

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#247]
The goal is that this will help reduce the random exceptions from #35. A pivot from #230.

We have a strong hunch that the `Connection.get()` function in `app/ui/connection.py` is returning a snowpark `Session` which is not thread-safe and being used by multiple threads.

https://docs.streamlit.io/library/api-reference/connections/st.experimental_connection seems like it could help the local development (which is also used by Cypress tests) inconsistency. Spend no more than half a day.

**Comment by rymurr** [comment]
going to move out of this sprint since we see much more stable tests now
