### ISSUE TITLE
UI tests: create a method of detecting whether all the objects on the page finished loading successfully

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#248]
It would be great to have a generic method for our OpsCenter tests that confirms that objects on the page have finished loading, so rest of the test can proceed successfully.

**Comment by susannahmarcus** [comment]
merged first version of this and added/tested on the first test on queries.spec.cy. It'll evolve as it's integrated into other areas, but as it is that test seems to consistently pass.

**Comment by susannahmarcus** [comment]
commit: 248: Add loading check method (#274) 
hash: 052befe86c862b3fd097518ac5495eb08de99306
