### ISSUE TITLE
`REPORTING.ENRICHED_QUERY_HISTORY_DAILY' declared 77 column(s), but view query produces 81 column(s)

### ISSUE THREAD

**Issue by jinfengni** [sundeck-io/OpsCenter#254]
The error was hit on latest `main` with commit  `38616f948f8b7060b595883e4af9a49048ca70c9`.  It happened after a fresh install of App.

```
drop database db_used_for_app;

poetry run python deploy/devdeploy.py -p local_dev

```

**Comment by joshelser** [comment]
The commit from #243 appears to have caused this.
