### ISSUE TITLE
OpsCenter doesn't guard against name conflicts in labeled query history

### ISSUE THREAD

**Issue by jacques-n** [sundeck-io/OpsCenter#26]
The way that labels work is that each new label is created as an additional column in `REPORTING.LABELED_QUERY_HISTORY` view. This works fine in practice and label names are always treated as quoted identifiers. Label modification automatically ensures verification that label names are unique. However, we have no operation that ensures that a label name doesn't overlap with an existing query history column name. If a user tries to create a duplicate name, I believe OpsCenter will get into a invalid partial state where we've saved the labels definition but then fail to update the view. I believe that means all future label edits will fail until the offending label name is modified (or the label is deleted).

**Comment by jinfengni** [comment]
I tried two cases:

1. New label name conflicts with existing label name. 
It hit error `Duplicate label name found. Please use a distinct name.`. This is expected results as explained in this ticket. 

2. New label name conflicts with COLUMN NAME in query_history.
Tried to create a label with name `QUERY_ID`. It hit the following error:

```
SnowparkSQLException: (1304): 01adfc35-0603-6527-0062-500302e057a2: 002025 (42S21): Uncaught exception of type 'STATEMENT_ERROR' on line 27 at position 4 : Uncaught exception of type 'STATEMENT_ERROR' on line 35 at position 4 : SQL compilation error: duplicate column name 'QUERY_ID'
``` 

Looks like when new label name conflicts with query history column name, Snowflake will fail the operation and raise error / Exception.  However,  the new label still got created in the App.
