### ISSUE TITLE
Workflow changes for instability of cypress tests

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#292]
@susannahmarcus was telling me how she had committed a cypress test change which passed on the pull request and then failed on the cypress test on `main`. It had been passing consistently on her local machine. Obviously, this is super frustrating and hard to know when changes are being effective if they don't fail on the pull request.

The assumption is that we just haven't found the "right" set of changes to make the tests reliably pass with the streamlit/github action workers yet. Can we do anything to help suss out instabilities faster?

Thinking out loud:
* Can we tell cypress to always run tests N times? A quick glance with her seemed to indicate they only supported re-run if the test fails.
* Can we inject CPU or network throttling into the Cypress browser? https://github.com/WordPress/gutenberg/pull/18770 it seems like it would be possible, but I'm not sure how to plug that into Cypress.
* Can we re-run the cypress job multiple times when a PR is changing the cypress tests?

The latter is the only one I would know how to do off the top of my head. If this remains a frustration, we can decide if we think one of these approaches might help.

**Comment by joshelser** [comment]
https://dev.to/walmyrlimaesilv/how-to-run-a-test-multiple-times-with-cypress-to-prove-it-is-stable-3c0k this is what I was hoping would be an OOTB option for Cypress. If we know that a specific test is giving us troubles, we could wrap it in a retry loop with lodash.

**Comment by susannahmarcus** [comment]
honestly, the addition of adding multiple runs on cypress changing prs would definitely be an improvement. My number one worry though– and this might mess things up– is that it could overwrite artifacts of previous runs each time it runs again... is there a way to make sure we can keep the failures from _each_ run?
