### ISSUE TITLE
Seeing small amounts of query duplication in enriched_query_history

### ISSUE THREAD

**Issue by jacques-n** [sundeck-io/OpsCenter#31]
There appears to be a small amount of duplication occurring in `REPORTING.ENRICHED_QUERY_HISTORY`. It is likely due to some kind of issue with boundary conditions associated with the incremental updates. Easiest way to understand how prevalent the problem is was by running this query:

```
with t1 as (select count(*) dupes from (select query_id from reporting.enriched_query_history group by all having count(*) > 1)),
t2 as (select count(*) total from reporting.enriched_query_history)
select dupes*1.0/total as dupe_fraction from t1, t2
```

On one of our random datasets that has had the app installed for a couple of weeks, we see: `0.000006`. Not clear yet whether this increases the more times the query history update procedure runs.

As part of this fix, we should also look if warehouse events updates suffer the same problem (since they are built on the same basic logic).

**Comment by rymurr** [comment]
Having another look i still see the same percentage of duplication. What I did notice is that all of these dup queries cross a day boundary. 

Looking at `select * from reporting.enriched_query_history where query_id in (select query_id from reporting.enriched_query_history group by all having count(*) > 1);` we can see a few things:
* every query shows up twice
* every query crosses midnight boundary
* the `cost` column is different
* the ratio of the duration before and after the day boundary are the same as the cost ratios

From this we can determine that the algorithm is actually working correctly and the cost is being split across the two days that it ran across.
