### ISSUE TITLE
Update README file for Cypress - typescript is a requirement now

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#321]
I checked out main and got this error:

```
Error: You are attempting to run a TypeScript file, but do not have TypeScript installed. Ensure you have 'typescript' installed to enable TypeScript support.
```
To install:

`npm install typescript --save-dev`

**Comment by joshelser** [comment]
What changed that started requiring this? I just ran into this today cc/ @susannahmarcus

**Comment by susannahmarcus** [comment]
ah, sorry that was commit 5115498450c998acf9fc2a3f2b91e2627b579a04. That said, you should just get rid of your node modules and do a yarn install. It's much easier to go that route.

**Comment by susannahmarcus** [comment]
this step is covered in the cypress build. Are you both seeing this outside of trying to build the cypress tests? I just want to make sure where I would need to update the README.

**Comment by susannahmarcus** [comment]
the above step is covered in the cypress README.md so I'm going to close this.
