### ISSUE TITLE
Add some sort of error prefix/suffix to all exception messages for the e2e tests

### ISSUE THREAD

**Issue by susannahmarcus** [sundeck-io/OpsCenter#340]
There is a certain type of exception banner one can get in opscenter which does not have any indication from a e2e test perspective that this is _in fact_ an exception. It would be helpful if all exception text started with the same prefix or ended with a suffix that would allow the tests to know that's on the screen. 

Examples: 
`Something went wrong: [error text]`
`Error: [error text]`
`[error text] (sundeck exception #[blah blah])`

here's the error banner I'm referencing for this:
![example_exception](https://github.com/sundeck-io/OpsCenter/assets/66705808/bff983b3-4309-40df-abc3-1668c3e5ac94)

**Comment by joshelser** [comment]
I would be _very_ happy if we adopted some kind of pattern around error messages to avoid a bunch of fixing of unit tests (like I just got through in #331). I think we could solve both of these at the same time.

**Comment by susannahmarcus** [comment]
**_NOTE_**: This is blocking the addition of any negative tests since those tests will _by nature be flaky_ because they'll need to look for exact language. Until we can get a suffix/preffix for these error messages, there is no way to make a non-flaky test to see if there are this type of errors on the screen.
