### ISSUE TITLE
Improve long/fixed timeouts in Cypress tests

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#38]
We have a number of long timeouts to minimize flakiness in the Cypress tests because a UI element is not updated quickly enough. The downside is that this is onerous to write such tests, but also drives up the cost of pre-commit testing (because the tests have to run for a significantly longer period of time).

**Comment by vqmarkman** [comment]
These commits should address most of the issues. Every failing test after that should be debugged separately.
I will keep an eye on the runs. Closing.
