### ISSUE TITLE
OUTCOME column in PROBE_ACTIONS table has SQL error message despite probe notifications working

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#391]
executing `call admin.run_as_app('select * from internal.probe_actions');`

returns:
<img width="1412" alt="Screenshot 2023-09-29 at 11 20 12 AM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/75749170-e0b8-4b90-838d-ee5cd267dfea">

This commit: `38a596b9dff1aaf8d4ffd26b62909e8618730aa6`

we should fix it before we ship + regression test in pytest framework is in order.

**Comment by joshelser** [comment]
Do you observe the probes running, @vqmarkman ?

**Comment by vqmarkman** [comment]
yes and reporting to slack and email.
