### ISSUE TITLE
user can submit a probe/label in sql that will have an error in the UI that takes buttons

### ISSUE THREAD

**Issue by susannahmarcus** [sundeck-io/OpsCenter#399]
(I've seen this on the edit form as well as listing, though I can only currently recreate with the listing page for screenshot purposes)

When the user creates a probe using sql that doesn't throw any error, the ui can error out when displaying this and takes away all of the action buttons (edit & delete \ cancel & update) so the user is stuck resolving this in sql:

![Screen Shot 2023-10-02 at 2 48 32 PM](https://github.com/sundeck-io/OpsCenter/assets/66705808/081a2b42-d9b7-4d74-b1bb-d2e3983bd8e4)

This can be seen in the form page due to the logic that causes issue #40. If you make a failing probe and were last in edit, you can get stuck on a failed page. In the listing page, it's essentially the same thing since you can't delete the breaking row.

**Comment by joshelser** [comment]
> When the user creates a probe using sql that doesn't throw any error

That sounds like we have a bug in the crud procedure for probes then. Any probe that you can create in SQL should work fine in the UI, and vice versa.

**Comment by susannahmarcus** [comment]
From what I've seen of the code, it's dependent on something having a value to check if it has a length. If we have some null checks there, it could fix this.
