### ISSUE TITLE
While trying to create one more weekend schedule ended up with Finish time of 12:15am

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#435]
Attaching video of the end result. Have absolutely no idea how it happened.
I thought I just simply clicked on "+" button and then saved schedule that starts from 12:15.
Schedule was not created AND finish time on the original schedule reset to 12:15am

Tried to reproduce it - no luck. Will try again ...

https://github.com/sundeck-io/OpsCenter/assets/104043363/ac73c0a1-6962-467e-9ae0-478dcceecfa8

**Comment by joshelser** [comment]
The only possible explanation I have is that this was running without #417 . I double-checked the transaction logic (by throwing an error) and verified that the first row update is rolled back if we throw an exception in th esecond.

If we can't reproduce this, let's close for now and reopen when we can.
