### ISSUE TITLE
auto-check enable box after user makes a schedule, give them a hint to uncheck if they're not ready

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#437]
I don't like the idea of computers doing things without me telling them to do something, but, if a user is creating a warehouse schedule, it's reasonable to think that they want to do this.

If the schedule is disabled and the user is making modifications to the schedule, enable the schedules for them and update the toast to indicate we did this.

split from #436

**Comment by joshelser** [comment]
@studiosciences this is what we were talking about earlier today. Thoughts?

In this screenshot, I have created some warehouse schedules (by clicking the + button on the right hand side and submitting a form). However, my schedules won't be applied because the schedules are still "disabled"

<img width="2833" alt="Screenshot 2023-10-06 at 12 54 21 PM" src="https://github.com/sundeck-io/OpsCenter/assets/67863/08279dbf-47eb-4d59-be42-4da0473ae857">

Once the user checks the checkbox circled above the schedules defined on the page would then be applied. It's very easy to add the new schedule and forget to check that box.

The suggestion is, after the user makes a change to a schedule (adds new or updates existing), the application would automatically enable all of the schedules for this warehouse. If a user _doesn't_ want the schedules to run after changing a schedule, they would have to uncheck that checkbox.

**Comment by studiosciences** [comment]
Side comment, "Schedule" means two things here. I recommend calling the rows "Rules" or something different.

Options:
1. Add a message to the bottom of the form saying something like, "This rule will not be active until the schedule is enabled."
    - I realize we have very limited UI options, so we could make this a table with one column heading "Note", or a text area that is disabled with a label of "Note".
2. Add a second button for "Create & Enable Schedule". 

I prefer the first option, which can apply to edit and create.

**Comment by joshelser** [comment]
> Side comment, "Schedule" means two things here. I recommend calling the rows "Rules" or something different.

Fair point. I think as we talk about this to others (those outside of Sundeck), it will become clear what word is best :). I appreciate your suggestion but will respectfully keep it in my back pocket for now.

> I prefer the first option, which can apply to edit and create.

Sure, that's easy enough to add.

To be clear, you think such a help text is sufficient instead of automatically enabling the schedule or you are suggesting help text in addition to automatically enabling the schedule on update/create?

**Comment by studiosciences** [comment]
I'm assuming people are going to create a bunch of rules in the schedule before they enable it, so it doesn't make sense to auto enable.

If the enable/disable state could be more prominent, such as in a banner, that would be better. Not sure what options exist.

> This schedule is not yet active. [Enable]()

**Comment by joshelser** [comment]
<img width="2832" alt="Screenshot 2023-10-06 at 5 36 45 PM" src="https://github.com/sundeck-io/OpsCenter/assets/67863/6d359917-43fe-4842-bfbf-11b526e05b7d">

comin' in #432
