### ISSUE TITLE
Investigate the app logging framework and if suitable add some debug logs

### ISSUE THREAD

**Issue by rymurr** [sundeck-io/OpsCenter#57]
It is hard to debug and investigate what is going on in teh streamlit app. There is a logging framework [here](https://docs.snowflake.com/en/developer-guide/native-apps/setting-up-logging-and-events) but its not clear if its suitable.

If the logging capabilities are suitable we should instrument our code with some log statements for easy to solve problems, eg if the materialization job isn't finishing.

**Comment by joshelser** [comment]
Positive side: it's actually possible to use snowflake scripting to answer some easy questions like:

* Does the snowflake account have an event table associated with it?
* Does the application have the `share_events_with_provider` property set to `true`?

Negative side: none of these commands (`show parameters .. in account`, `describe applicat`) work inside of streamlit.

* `Stored procedure execution error: Unsupported statement type 'DESCRIBE APPLICATION'.`
* `Stored procedure execution error: Unsupported statement type 'SHOW PARAMETERS'.`

This means we really can't do anything to help the user set up the event table and sharing. They have to do it all themselves.
