### ISSUE TITLE
Labels negative test failed with the failure to find an element (this is a test problem and not a product issue)

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#76]
Failed here: https://github.com/sundeck-io/OpsCenter/actions/runs/5659211804 
See attached video

https://github.com/sundeck-io/OpsCenter/assets/104043363/f2ab55b5-e62a-4647-9a87-c0830dfe364d

The problem in this test is that when "Cancel" button is clicked and we are brought back to the list of labels, cypress can't find label element on the page. I thought I resolved this issue by reloading the page, but it does not seem to be the case.

Need to find different a solution.

**Comment by joshelser** [comment]
Thanks for filing this, Vicky! If you aren't able to get to the bottom of this today, could you please temporarily revert #58 or skip these tests that are now failing?

I also noticed a settings.spec.cy.js failure which looks to be similar to these label failures in https://github.com/sundeck-io/OpsCenter/actions/runs/5667117995/job/15355204886

**Comment by vqmarkman** [comment]
@joshelser , I just submitted PR: https://github.com/sundeck-io/OpsCenter/pull/81 to take flaky tests out until I figure out what is causing that.
"Settings" failure is something different that I'm still looking into.
