### ISSUE TITLE
Introduce Dynamic Grouped labels

### ISSUE THREAD

**Issue by rymurr** [sundeck-io/OpsCenter#87]
Currently a grouped set of labels consistes of several labels each with a condition. We will add a new type of grouped label which is defined by a function/sql udf.

for example if we wanted a grouped label to be all qtag sources then we could define a funciton which extracted the source from the query qtag (and qtag-less queries would fall into the ungrouped bucket).

This could also be used to categorise which client a query came from or to easily categorise a query by size (eg with a case statement on no of returned rows).

Note: in this first insnace we will not worry too much about staleness of the group. If a new member has been added the user will have to manually re-save the label for it to be picked up.

**Comment by rymurr** [comment]
Thinking of impl: 
Add new 'create function label' button to labels page. The function button takes a SQL function which returns a string or null. Label in group is assigned by return value of function (or is ungrouped if null)

**Comment by jinfengni** [comment]
initial thoughts of implementation details:

- add a new row in `internal.dynamic_grouped_labels` : `(group_name string, label_condition_expr string, group_created_at / group_modified_at timestamp)`.  `label_condition_expr` should return a string value. 
- add a column in `reporting.labeled_query_history` view:   `case when $label_value_expr is not null $label_value_expr else 'Others' end as $group_name`
- The dynamic `group_name ` should be added to the list where `static` groups are present in UI dropbox.

**Comment by rymurr** [comment]
why not just add a label_condition_expr column to the labels table? why would a dynamic label be different from a static one?

**Comment by jinfengni** [comment]
Maybe adding a new boolean column `is_dynamic` column to `labels` table?  Earlier on, I thought there is no clear way to different the static ungrouped labels / grouped labels from the dynamic grouped labels. 

upgrouped labels :  name is not null,  group name/rank must be null
static grouped labels: name is not null, group name / rank must not be null
dynamic grouped labels: name is null, group name must not be null,  rank must be null.  

Also, if we put all of them into `labels` table, it would not easy to enforce some constraints at db/table level.  For instance, we want to ensure group name is unique for the dynamic group labels.  The ungrouped labels' name should be unique.  It's fine to enforce them in the store procedure before we insert the data row. But it would be ideal if we can enforce the constraint by DB itself.

**Comment by rymurr** [comment]
> Maybe adding a new boolean column is_dynamic column to labels table
Great idea

> But it would be ideal if we can enforce the constraint by DB
I agree this would  be nice but it sounds awful hard.  For now I would just rely on verification in the stored proc
