### ISSUE TITLE
Deleting last label in a group leaves user on an tab with no group name

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#90]
From https://github.com/sundeck-io/OpsCenter/actions/runs/5674876609/job/15387558344

https://github.com/sundeck-io/OpsCenter/assets/67863/dfa35b69-c6d0-44d3-9af0-44b8abb290e5

When we delete the last label on a group, we are left on an "empty" group tab. I was able to reproduce this in a deployed app.

<img width="1141" alt="Screenshot 2023-07-27 at 12 40 42 PM" src="https://github.com/sundeck-io/OpsCenter/assets/67863/c714d8ed-29f9-4cb4-bf01-b8b45f4cdaff">

It looks like we have some kind of edge case that we need to detect and try to load the ungrouped labels tab.

**Comment by joshelser** [comment]
@vqmarkman I think you've been spending more time in this code recently than I have. I'm surprised that this test would not be failing deterministically yet we are having successful cypress tests against `main`. Any thoughts?

**Comment by vqmarkman** [comment]
@joshelser, this is the same issue as #76 
rebasing should take these tests out of circulation. I will fix them today. Hopefully ...
